Repository Project-Complete/Complete_BE, pull requests merged in 2024-04, with the labels that each got.

#91 fix: Swagger 요청 Server URL error 수정
  src/main/java/org/complete/challang/config/SwaggerConfig.java
Labels: bug

#92 refactor: 주류 조회 isActive 반영 및 주류 리스트 total_page 반환
  src/main/java/org/complete/challang/app/common/dto/PageInfoDto.java
  src/main/java/org/complete/challang/app/drink/controller/dto/response/DrinkListFindResponse.java
  src/main/java/org/complete/challang/app/drink/controller/dto/response/DrinkPageResponse.java
  src/main/java/org/complete/challang/app/drink/domain/entity/Drink.java
  src/main/java/org/complete/challang/app/drink/domain/entity/spec/DrinkSpec.java
  src/main/java/org/complete/challang/app/drink/domain/repository/DrinkCustomRepositoryImpl.java
  src/main/java/org/complete/challang/app/drink/domain/repository/DrinkRepository.java
  src/main/java/org/complete/challang/app/drink/service/DrinkService.java
Labels: feature, refactor

#95 feat: 주류 리뷰 조회 관련 API 수정
  src/main/java/org/complete/challang/app/account/user/controller/UserController.java
  src/main/java/org/complete/challang/app/review/controller/ReviewController.java
  src/main/java/org/complete/challang/app/review/controller/dto/item/ReviewDto.java
  src/main/java/org/complete/challang/app/review/controller/dto/response/ReviewDetailResponse.java
  src/main/java/org/complete/challang/app/review/service/ReviewService.java
Labels: feature, refactor

#96 refactor: Presigned url duration 조정
  src/main/java/org/complete/challang/app/common/service/S3Service.java
Labels: refactor

#98 feat: findUserProfile API url 추가
  src/main/java/org/complete/challang/app/account/user/controller/UserController.java
Labels: feature
