Repository Project-Complete/Complete_BE, pull requests merged in 2024-07, with the labels that each got.

#139 feature: 주류 조합 정렬 기준 추가 및 삭제 주류조합 조회시 error 처리
  src/main/java/org/complete/challang/app/combination/domain/entity/CombinationSortCriteria.java
  src/main/java/org/complete/challang/app/combination/domain/repository/CombinationBoardCustomRepositoryImpl.java
  src/main/java/org/complete/challang/app/combination/service/CombinationBoardService.java
  src/main/java/org/complete/challang/app/common/exception/ErrorResponse.java
  src/main/java/org/complete/challang/app/common/exception/SuccessCode.java
  src/main/java/org/complete/challang/app/drink/domain/entity/criteria/DrinkSortCriteria.java
  src/main/java/org/complete/challang/app/drink/domain/repository/DrinkCustomRepositoryImpl.java
Labels: feature, refactor

#141 style: 코딩 컨벤션수정
  src/main/java/org/complete/challang/app/review/service/ReviewService.java
Labels: test

#143 feat: 주류 및 주류 조합 keyword 검색 및 주류 검색 기능 구현
  src/main/java/org/complete/challang/app/combination/controller/CombinationBoardController.java
  src/main/java/org/complete/challang/app/combination/domain/repository/CombinationBoardCustomRepositoryImpl.java
  src/main/java/org/complete/challang/app/common/controller/MainController.java
  src/main/java/org/complete/challang/app/common/repository/MainCustomRepository.java
  src/main/java/org/complete/challang/app/common/repository/MainCustomRepositoryImpl.java
  src/main/java/org/complete/challang/app/common/repository/SearchCustomRepository.java
  src/main/java/org/complete/challang/app/common/repository/SearchCustomRepositoryImpl.java
  src/main/java/org/complete/challang/app/common/service/MainService.java
  src/main/java/org/complete/challang/app/common/service/SearchService.java
  src/main/java/org/complete/challang/app/drink/controller/DrinkController.java
  src/main/java/org/complete/challang/app/drink/domain/repository/DrinkCustomRepositoryImpl.java
  src/main/java/org/complete/challang/app/drink/service/DrinkService.java
Labels: feature, refactor

#146 feat: 특정 User 관련 주류 조합 리스트 조회 기능 구현
  src/main/java/org/complete/challang/app/account/user/controller/UserController.java
  src/main/java/org/complete/challang/app/account/user/service/UserService.java
  src/main/java/org/complete/challang/app/combination/domain/repository/CombinationBoardCustomRepository.java
  src/main/java/org/complete/challang/app/combination/domain/repository/CombinationBoardCustomRepositoryImpl.java
Labels: feature

#147 feat: develop 브랜치 master 브랜치로 PR
  src/main/java/org/complete/challang/app/account/user/controller/UserController.java
  src/main/java/org/complete/challang/app/account/user/service/UserService.java
  src/main/java/org/complete/challang/app/combination/controller/CombinationBoardController.java
  src/main/java/org/complete/challang/app/combination/controller/CombinationCommentController.java
  src/main/java/org/complete/challang/app/combination/controller/CombinationController.java
  src/main/java/org/complete/challang/app/combination/controller/dto/item/CombinationCreateUpdateDto.java
  src/main/java/org/complete/challang/app/combination/controller/dto/item/CombinationFindDto.java
  src/main/java/org/complete/challang/app/combination/controller/dto/item/EtcCombinationFindDto.java
  src/main/java/org/complete/challang/app/combination/controller/dto/request/CombinationCommentCreateRequest.java
  src/main/java/org/complete/challang/app/combination/controller/dto/request/CombinationCommentUpdateRequest.java
  src/main/java/org/complete/challang/app/combination/controller/dto/response/CombinationBoardFindResponse.java
  src/main/java/org/complete/challang/app/combination/controller/dto/response/CombinationBoardListFindResponse.java
  src/main/java/org/complete/challang/app/combination/controller/dto/response/CombinationCommentPageResponse.java
  src/main/java/org/complete/challang/app/combination/controller/dto/response/CombinationCommentResponse.java
  src/main/java/org/complete/challang/app/combination/domain/entity/Combination.java
  src/main/java/org/complete/challang/app/combination/domain/entity/CombinationBoard.java
  src/main/java/org/complete/challang/app/combination/domain/entity/CombinationBoardBookmark.java
  src/main/java/org/complete/challang/app/combination/domain/entity/CombinationBoardLike.java
  src/main/java/org/complete/challang/app/combination/domain/entity/CombinationComment.java
  src/main/java/org/complete/challang/app/combination/domain/entity/CombinationSortCriteria.java
  src/main/java/org/complete/challang/app/combination/domain/repository/CombinationBoardCustomRepository.java
  src/main/java/org/complete/challang/app/combination/domain/repository/CombinationBoardCustomRepositoryImpl.java
  src/main/java/org/complete/challang/app/combination/domain/repository/CombinationCommentCustomRepository.java
  src/main/java/org/complete/challang/app/combination/domain/repository/CombinationCommentCustomRepositoryImpl.java
  src/main/java/org/complete/challang/app/combination/domain/repository/CombinationCommentRepository.java
  src/main/java/org/complete/challang/app/combination/service/CombinationBoardService.java
  src/main/java/org/complete/challang/app/combination/service/CombinationCommentService.java
  src/main/java/org/complete/challang/app/common/controller/MainController.java
  src/main/java/org/complete/challang/app/common/exception/ErrorCode.java
  src/main/java/org/complete/challang/app/common/exception/ErrorResponse.java
  src/main/java/org/complete/challang/app/common/exception/SuccessCode.java
  src/main/java/org/complete/challang/app/common/exception/SuccessResponse.java
  src/main/java/org/complete/challang/app/common/repository/MainCustomRepository.java
  src/main/java/org/complete/challang/app/common/repository/MainCustomRepositoryImpl.java
  src/main/java/org/complete/challang/app/common/repository/SearchCustomRepository.java
  src/main/java/org/complete/challang/app/common/repository/SearchCustomRepositoryImpl.java
  src/main/java/org/complete/challang/app/common/service/MainService.java
  src/main/java/org/complete/challang/app/common/service/SearchService.java
  src/main/java/org/complete/challang/app/drink/controller/DrinkController.java
  src/main/java/org/complete/challang/app/drink/domain/entity/FoodStatistic.java
  src/main/java/org/complete/challang/app/drink/domain/entity/SituationStatistic.java
  src/main/java/org/complete/challang/app/drink/domain/entity/TasteStatistic.java
  src/main/java/org/complete/challang/app/drink/domain/entity/criteria/DrinkSortCriteria.java
  src/main/java/org/complete/challang/app/drink/domain/repository/DrinkCustomRepositoryImpl.java
  src/main/java/org/complete/challang/app/drink/service/DrinkService.java
  src/main/resources/application-dev.yml
Labels: feature

#148 feat: Redis 도입
  .github/workflows/dev-actions.yml
  .github/workflows/gradle.yml
  build.gradle
  docker-compose.yml
  src/main/java/org/complete/challang/app/account/jwt/Token.java
  src/main/java/org/complete/challang/app/account/jwt/TokenProvider.java
  src/main/java/org/complete/challang/app/account/jwt/filter/TokenAuthenticationFilter.java
  src/main/java/org/complete/challang/app/account/oauth2/handler/OAuth2SuccessHandler.java
  src/main/java/org/complete/challang/app/common/domain/entity/BaseEntity.java
  src/main/java/org/complete/challang/app/drink/controller/dto/item/DrinkTypeDto.java
  src/main/java/org/complete/challang/app/drink/controller/dto/item/FlavorStatisticDto.java
  src/main/java/org/complete/challang/app/drink/controller/dto/item/FoodStatisticDto.java
  src/main/java/org/complete/challang/app/drink/controller/dto/item/ManufacturerDto.java
  src/main/java/org/complete/challang/app/drink/controller/dto/item/PackageDto.java
  src/main/java/org/complete/challang/app/drink/controller/dto/item/TasteAverageStatisticDto.java
  src/main/java/org/complete/challang/app/drink/controller/dto/response/DrinkFindResponse.java
  src/main/java/org/complete/challang/app/drink/domain/entity/SituationStatistic.java
  src/main/java/org/complete/challang/app/drink/domain/repository/DrinkCacheRepository.java
  src/main/java/org/complete/challang/app/drink/service/DrinkService.java
  src/main/java/org/complete/challang/app/review/service/ReviewService.java
  src/main/java/org/complete/challang/config/RedisConfig.java
  src/main/resources/application-dev.yml
  src/main/resources/application.yml
  src/main/resources/logback/console-appender.xml
  src/main/resources/logback/discord-appender.xml
  src/main/resources/logback/logback-spring.xml
Labels: feature, refactor, chore

#150 feat: Cloud Front를 이용한 CDN 적용
  .github/workflows/dev-actions.yml
  src/main/java/org/complete/challang/app/common/controller/dto/response/PreSignedUrlFindResponse.java
  src/main/java/org/complete/challang/app/common/service/S3Service.java
  src/main/resources/application-cloud.yml
Labels: feature
