Repository Project-Complete/Complete_BE, pull requests merged in 2024-02, with the labels that each got.

#22 chore: Swagger 전역 설정
  build.gradle
  src/main/java/org/complete/challang/common/config/SwaggerConfig.java
Labels: chore

#24 소셜로그인 기능 구현
  build.gradle
  src/main/java/org/complete/challang/ChallangApplication.java
  src/main/java/org/complete/challang/account/jwt/Token.java
  src/main/java/org/complete/challang/account/jwt/TokenProvider.java
  src/main/java/org/complete/challang/account/jwt/filter/TokenAuthenticationFilter.java
  src/main/java/org/complete/challang/account/jwt/util/TokenUtil.java
  src/main/java/org/complete/challang/account/oauth2/CustomOAuth2User.java
  src/main/java/org/complete/challang/account/oauth2/handler/OAuth2FailureHandler.java
  src/main/java/org/complete/challang/account/oauth2/handler/OAuth2SuccessHandler.java
  src/main/java/org/complete/challang/account/oauth2/service/CustomOAuth2UserService.java
  src/main/java/org/complete/challang/account/oauth2/userinfo/OAuth2UserInfo.java
  src/main/java/org/complete/challang/account/oauth2/userinfo/OAuth2UserInfoFactory.java
  src/main/java/org/complete/challang/account/oauth2/userinfo/impl/GoogleOAuth2UserInfo.java
  src/main/java/org/complete/challang/account/oauth2/userinfo/impl/KakaoOAuth2UserInfo.java
  src/main/java/org/complete/challang/account/oauth2/userinfo/impl/NaverOAuth2UserInfo.java
  src/main/java/org/complete/challang/account/user/domain/entity/RoleType.java
  src/main/java/org/complete/challang/account/user/domain/entity/User.java
  src/main/java/org/complete/challang/account/user/domain/repository/UserRepository.java
  src/main/java/org/complete/challang/config/SecurityConfig.java
Labels: feature

#25 feat: 주류 리뷰 작성 api 개발
  build.gradle
  src/main/java/org/complete/challang/common/exception/ErrorCode.java
  src/main/java/org/complete/challang/drink/domain/entity/Drink.java
  src/main/java/org/complete/challang/drink/domain/entity/SituationStatistic.java
  src/main/java/org/complete/challang/drink/domain/entity/TasteStatistic.java
  src/main/java/org/complete/challang/drink/domain/repository/DrinkRepository.java
  src/main/java/org/complete/challang/drink/domain/repository/FoodRepository.java
  src/main/java/org/complete/challang/review/controller/ReviewController.java
  src/main/java/org/complete/challang/review/controller/dto/item/SituationDto.java
  src/main/java/org/complete/challang/review/controller/dto/item/TasteDto.java
  src/main/java/org/complete/challang/review/controller/dto/request/ReviewCreateRequest.java
  src/main/java/org/complete/challang/review/controller/dto/response/ReviewCreateResponse.java
  src/main/java/org/complete/challang/review/domain/entity/Review.java
  src/main/java/org/complete/challang/review/domain/repository/FlavorRepository.java
  src/main/java/org/complete/challang/review/domain/repository/ReviewRepository.java
  src/main/java/org/complete/challang/review/domain/repository/SituationRepository.java
  src/main/java/org/complete/challang/review/domain/repository/TasteRepository.java
  src/main/java/org/complete/challang/review/service/ReviewService.java
  src/main/java/org/complete/challang/test/TestController.java
  src/test/java/org/complete/challang/app/review/controller/ReviewControllerTest.java
  src/test/java/org/complete/challang/app/review/repository/ReviewRepositoryTest.java
  src/test/java/org/complete/challang/app/review/service/ReviewServiceTest.java
  src/test/java/org/complete/challang/util/LocalDateTimeTypeAdapter.java
Labels: feature, test

#26 feat: 주류 상세조회 구현
  build.gradle
  src/main/java/org/complete/challang/common/exception/ErrorCode.java
  src/main/java/org/complete/challang/drink/controller/DrinkController.java
  src/main/java/org/complete/challang/drink/domain/entity/Drink.java
  src/main/java/org/complete/challang/drink/domain/entity/DrinkDetailType.java
  src/main/java/org/complete/challang/drink/domain/entity/Food.java
  src/main/java/org/complete/challang/drink/domain/entity/Package.java
  src/main/java/org/complete/challang/drink/domain/entity/SituationStatistic.java
  src/main/java/org/complete/challang/drink/domain/entity/TasteStatistic.java
  src/main/java/org/complete/challang/drink/dto/response/DrinkFindResponse.java
  src/main/java/org/complete/challang/drink/dto/response/DrinkTypeFindResponse.java
  src/main/java/org/complete/challang/drink/dto/response/FlavorStatisticFindResponse.java
  src/main/java/org/complete/challang/drink/dto/response/FoodStatisticFindResponse.java
  src/main/java/org/complete/challang/drink/dto/response/ManufacturerFindResponse.java
  src/main/java/org/complete/challang/drink/dto/response/PackageFindResponse.java
  src/main/java/org/complete/challang/drink/dto/response/TagFindResponse.java
  src/main/java/org/complete/challang/drink/dto/response/TasteAverageStatistic.java
  src/main/java/org/complete/challang/drink/repository/DrinkQueryRepository.java
  src/main/java/org/complete/challang/drink/repository/DrinkQueryRepositoryImpl.java
  src/main/java/org/complete/challang/drink/repository/DrinkRepository.java
  src/main/java/org/complete/challang/drink/repository/FoodRepository.java
  src/main/java/org/complete/challang/drink/service/DrinkService.java
  src/main/java/org/complete/challang/review/domain/repository/ReviewFlavorRepository.java
  src/main/java/org/complete/challang/review/domain/repository/ReviewFoodRepository.java
  src/test/java/org/complete/challang/drink/common/adaptor/LocalDateTimeTypeAdaptor.java
  src/test/java/org/complete/challang/drink/controller/DrinkControllerTest.java
  src/test/java/org/complete/challang/drink/repository/DrinkRepositoryTest.java
  src/test/java/org/complete/challang/drink/service/DrinkServiceTest.java
  src/test/resources/application.yml
Labels: feature

#31 hotfix: 주류 상세기능 오류 수정
  src/main/java/org/complete/challang/drink/domain/repository/DrinkQueryRepositoryImpl.java
  src/main/java/org/complete/challang/drink/service/DrinkService.java
Labels: bug

#35 feat: 주류 리뷰 상세 조회 기능 구현
  src/main/java/org/complete/challang/common/exception/ErrorCode.java
  src/main/java/org/complete/challang/config/SecurityConfig.java
  src/main/java/org/complete/challang/review/controller/ReviewController.java
  src/main/java/org/complete/challang/review/controller/dto/item/SituationDto.java
  src/main/java/org/complete/challang/review/controller/dto/item/TasteDto.java
  src/main/java/org/complete/challang/review/controller/dto/response/ReviewDetailResponse.java
  src/main/java/org/complete/challang/review/service/ReviewService.java
Labels: feature

#37 chore: Github Actions Docker 적용
  .github/workflows/dev-actions.yml
  Dockerfile
  src/main/resources/application-dev.yml
  src/main/resources/application-jwt.yml
  src/main/resources/application-oauth.yml
  src/main/resources/application.yml
Labels: chore

#41 feat: 주류 리뷰 삭제 API 구현 및 생성, 조회 API 수정
  build.gradle
  src/main/java/org/complete/challang/account/jwt/Token.java
  src/main/java/org/complete/challang/account/jwt/filter/TokenAuthenticationFilter.java
  src/main/java/org/complete/challang/account/user/domain/repository/UserRepository.java
  src/main/java/org/complete/challang/common/domain/entity/BaseEntity.java
  src/main/java/org/complete/challang/common/exception/ErrorCode.java
  src/main/java/org/complete/challang/drink/domain/entity/Drink.java
  src/main/java/org/complete/challang/drink/domain/entity/SituationStatistic.java
  src/main/java/org/complete/challang/drink/domain/entity/TasteStatistic.java
  src/main/java/org/complete/challang/drink/domain/repository/DrinkRepository.java
  src/main/java/org/complete/challang/review/controller/ReviewController.java
  src/main/java/org/complete/challang/review/controller/dto/item/ReviewDto.java
  src/main/java/org/complete/challang/review/controller/dto/item/WriterDto.java
  src/main/java/org/complete/challang/review/controller/dto/response/ReviewDetailResponse.java
  src/main/java/org/complete/challang/review/domain/entity/Review.java
  src/main/java/org/complete/challang/review/domain/entity/ReviewSortCriteria.java
  src/main/java/org/complete/challang/review/domain/repository/ReviewRepository.java
  src/main/java/org/complete/challang/review/service/ReviewService.java
  src/test/java/org/complete/challang/app/review/controller/ReviewControllerTest.java
  src/test/java/org/complete/challang/app/review/service/ReviewServiceTest.java
Labels: bug, feature, chore

#49 feat: 평가기준별 주류 리스트 조회 기능 구현
  src/main/java/org/complete/challang/common/dto/PageInfoDto.java
  src/main/java/org/complete/challang/common/exception/ErrorCode.java
  src/main/java/org/complete/challang/drink/controller/DrinkController.java
  src/main/java/org/complete/challang/drink/controller/dto/response/DrinkListFindResponse.java
  src/main/java/org/complete/challang/drink/controller/dto/response/DrinkPageResponse.java
  src/main/java/org/complete/challang/drink/domain/entity/Drink.java
  src/main/java/org/complete/challang/drink/domain/entity/criteria/DrinkSortCriteria.java
  src/main/java/org/complete/challang/drink/domain/entity/spec/DrinkSpec.java
  src/main/java/org/complete/challang/drink/domain/repository/DrinkRepository.java
  src/main/java/org/complete/challang/drink/service/DrinkService.java
Labels: feature

#50 feat: 주류 추천 리스트 조회 기능 구현
  src/main/java/org/complete/challang/drink/controller/DrinkController.java
  src/main/java/org/complete/challang/drink/controller/dto/response/DrinkListFindResponse.java
  src/main/java/org/complete/challang/drink/domain/entity/criteria/DrinkTypeCriteria.java
  src/main/java/org/complete/challang/drink/domain/repository/DrinkRepository.java
  src/main/java/org/complete/challang/drink/service/DrinkService.java
Labels: feature

#52 feat: OAuth2 로그인 Redirect URL 반환 및 인증, 인가 Handler 적용
  .github/workflows/dev-actions.yml
  src/main/java/org/complete/challang/account/jwt/filter/TokenAuthenticationFilter.java
  src/main/java/org/complete/challang/account/oauth2/handler/OAuth2SuccessHandler.java
  src/main/java/org/complete/challang/account/oauth2/repository/HttpCookieOAuth2AuthorizationRequestRepository.java
  src/main/java/org/complete/challang/account/oauth2/util/CookieUtils.java
  src/main/java/org/complete/challang/common/exception/ErrorCode.java
  src/main/java/org/complete/challang/config/SecurityConfig.java
  src/main/java/org/complete/challang/handler/CustomAccessDeniedHandler.java
  src/main/java/org/complete/challang/handler/CustomAuthenticationEntryPoint.java
  src/main/resources/application-oauth.yml
  src/main/resources/application.yml
Labels: feature, chore

#53 feat: 주류 리뷰 목록 조회 검색 옵션 생성
  build.gradle
  src/main/java/org/complete/challang/account/user/controller/UserController.java
  src/main/java/org/complete/challang/account/user/controller/dto/response/UserProfileFindResponse.java
  src/main/java/org/complete/challang/account/user/domain/entity/User.java
  src/main/java/org/complete/challang/account/user/service/UserService.java
  src/main/java/org/complete/challang/config/QueryDSLConfig.java
  src/main/java/org/complete/challang/review/controller/ReviewController.java
  src/main/java/org/complete/challang/review/domain/repository/ReviewCustomRepository.java
  src/main/java/org/complete/challang/review/domain/repository/ReviewCustomRepositoryImpl.java
  src/main/java/org/complete/challang/review/service/ReviewService.java
Labels: feature, refactor, chore

#57 fix: 상세한 Exception 처리를 통한 bug 수정
  src/main/java/org/complete/challang/account/jwt/Token.java
  src/main/java/org/complete/challang/account/jwt/filter/TokenAuthenticationFilter.java
  src/main/java/org/complete/challang/account/oauth2/handler/OAuth2FailureHandler.java
  src/main/java/org/complete/challang/account/oauth2/handler/OAuth2SuccessHandler.java
  src/main/java/org/complete/challang/common/exception/ErrorCode.java
  src/main/java/org/complete/challang/common/exception/ErrorResponse.java
  src/main/java/org/complete/challang/common/exception/FilterErrorResponse.java
  src/main/java/org/complete/challang/common/exception/GlobalExceptionHandler.java
  src/main/java/org/complete/challang/handler/CustomAccessDeniedHandler.java
  src/main/java/org/complete/challang/handler/CustomAuthenticationEntryPoint.java
  src/main/resources/application.yml
Labels: bug

#58 feat: S3 pre-signed url 요청 기능 구현
  .github/workflows/dev-actions.yml
  build.gradle
  src/main/java/org/complete/challang/common/controller/S3Controller.java
  src/main/java/org/complete/challang/common/controller/dto/request/PreSignedUrlGetRequest.java
  src/main/java/org/complete/challang/common/controller/dto/response/PreSignedUrlGetResponse.java
  src/main/java/org/complete/challang/common/exception/ErrorCode.java
  src/main/java/org/complete/challang/common/service/S3Service.java
  src/main/java/org/complete/challang/config/S3Config.java
  src/main/java/org/complete/challang/config/SecurityConfig.java
  src/main/resources/application-cloud.yml
  src/main/resources/application.yml
Labels: feature

#62 fix: 팔로우 관련 에러 수정
  src/main/java/org/complete/challang/account/user/domain/repository/FollowRepository.java
  src/main/java/org/complete/challang/account/user/service/UserService.java
  src/main/java/org/complete/challang/config/SecurityConfig.java
Labels: bug

#63 feat: 주류 타입별 리스트 조회 구현
  src/main/java/org/complete/challang/account/oauth2/repository/HttpCookieOAuth2AuthorizationRequestRepository.java
  src/main/java/org/complete/challang/common/exception/GlobalExceptionHandler.java
  src/main/java/org/complete/challang/drink/domain/entity/criteria/DrinkSortCriteria.java
  src/main/java/org/complete/challang/drink/domain/repository/DrinkCustomRepository.java
  src/main/java/org/complete/challang/drink/domain/repository/DrinkCustomRepositoryImpl.java
  src/main/java/org/complete/challang/drink/domain/repository/DrinkRepository.java
  src/main/java/org/complete/challang/drink/service/DrinkService.java
Labels: feature

#67 fix: 리뷰 작성 API 에러 수정
  src/main/java/org/complete/challang/review/controller/dto/item/SituationDto.java
  src/main/java/org/complete/challang/review/controller/dto/item/TasteDto.java
  src/main/java/org/complete/challang/review/controller/dto/request/ReviewCreateRequest.java
  src/main/java/org/complete/challang/review/domain/entity/Review.java
  src/main/java/org/complete/challang/review/domain/entity/ReviewFlavor.java
  src/main/java/org/complete/challang/review/domain/entity/ReviewFood.java
  src/main/java/org/complete/challang/review/service/ReviewService.java
Labels: bug, feature, refactor

#70 feat: 주류 좋아요 로직 구현
  src/main/java/org/complete/challang/account/user/domain/entity/DrinkLike.java
  src/main/java/org/complete/challang/common/exception/ErrorCode.java
  src/main/java/org/complete/challang/common/exception/SuccessCode.java
  src/main/java/org/complete/challang/drink/controller/DrinkController.java
  src/main/java/org/complete/challang/drink/domain/entity/Drink.java
  src/main/java/org/complete/challang/drink/service/DrinkService.java
Labels: feature

#71 feat: 주류 관련 조회시 좋아요 여부 구현
  src/main/java/org/complete/challang/drink/controller/DrinkController.java
  src/main/java/org/complete/challang/drink/controller/dto/response/DrinkFindResponse.java
  src/main/java/org/complete/challang/drink/controller/dto/response/DrinkListFindResponse.java
  src/main/java/org/complete/challang/drink/domain/repository/DrinkCustomRepository.java
  src/main/java/org/complete/challang/drink/domain/repository/DrinkCustomRepositoryImpl.java
  src/main/java/org/complete/challang/drink/domain/repository/DrinkRepository.java
  src/main/java/org/complete/challang/drink/service/DrinkService.java
  src/test/java/org/complete/challang/drink/controller/DrinkControllerTest.java
  src/test/java/org/complete/challang/drink/service/DrinkServiceTest.java
Labels: feature, refactor

#74 fix: pre-signed url 요청 POST로 변경
  src/main/java/org/complete/challang/common/controller/S3Controller.java
Labels: bug, refactor

#78 comment: 각 API swagger 주석 추가
  src/main/java/org/complete/challang/account/user/controller/UserController.java
  src/main/java/org/complete/challang/review/controller/ReviewController.java
Labels: docs, chore

#80 comment: 주류 및 pre-signed url 관련 Swagger 수정
  src/main/java/org/complete/challang/common/controller/S3Controller.java
  src/main/java/org/complete/challang/drink/controller/DrinkController.java
Labels: docs, chore

#81 feat: 메인배너 추천 주류리스트 기능 구현
  src/main/java/org/complete/challang/config/QueryDSLConfig.java
  src/main/java/org/complete/challang/drink/controller/DrinkController.java
  src/main/java/org/complete/challang/drink/controller/dto/response/DrinkBannerListFindResponse.java
  src/main/java/org/complete/challang/drink/controller/dto/response/FoodStatisticFindResponse.java
  src/main/java/org/complete/challang/drink/controller/dto/response/ManufacturerFindResponse.java
  src/main/java/org/complete/challang/drink/domain/entity/criteria/DrinkSortCriteria.java
  src/main/java/org/complete/challang/drink/domain/repository/DrinkCustomRepository.java
  src/main/java/org/complete/challang/drink/domain/repository/DrinkCustomRepositoryImpl.java
  src/main/java/org/complete/challang/drink/service/DrinkService.java
Labels: feature
