Repository Project-Complete/Complete_BE, pull requests merged in 2024-05, with the labels that each got.

#103 feat: 메인 배너 조회 Situation(같이 마시면 좋은 사람) 반환
  src/main/java/org/complete/challang/app/drink/controller/dto/response/DrinkBannerListFindResponse.java
  src/main/java/org/complete/challang/app/drink/domain/repository/DrinkCustomRepositoryImpl.java
Labels: feature, refactor

#107 refactor: 좋아요 주류 목록 조회 리팩토링
  src/main/java/org/complete/challang/app/account/user/controller/UserController.java
  src/main/java/org/complete/challang/app/account/user/service/UserService.java
Labels: refactor

#108 feat: 리뷰 목록 조회 API 수정
  src/main/java/org/complete/challang/app/review/controller/dto/item/DrinkDto.java
  src/main/java/org/complete/challang/app/review/controller/dto/item/ReviewDto.java
  src/main/java/org/complete/challang/app/review/controller/dto/response/ReviewListFindResponse.java
Labels: feature

#109 feat: 사용자 팔로우 유무 API 개발
  src/main/java/org/complete/challang/app/account/user/controller/UserController.java
  src/main/java/org/complete/challang/app/account/user/controller/dto/response/FollowCheckResponse.java
  src/main/java/org/complete/challang/app/account/user/service/UserService.java
Labels: feature

#114 feat: Error 발생시 Discord Webhook 및 Logging AOP 적용
  build.gradle
  src/main/java/org/complete/challang/ChallangApplication.java
  src/main/java/org/complete/challang/app/aop/LoggingAspect.java
  src/main/java/org/complete/challang/app/common/exception/GlobalExceptionHandler.java
  src/main/resources/console-appender.xml
  src/main/resources/discord-appender.xml
  src/main/resources/logback-spring.xml
Labels: feature, refactor, chore

#115 feat: 주류 관련 API Validation 적용
  src/main/java/org/complete/challang/annotation/IdValid.java
  src/main/java/org/complete/challang/app/account/user/controller/UserController.java
  src/main/java/org/complete/challang/app/common/controller/MainController.java
  src/main/java/org/complete/challang/app/common/controller/S3Controller.java
  src/main/java/org/complete/challang/app/common/controller/dto/request/PreSignedUrlFindRequest.java
  src/main/java/org/complete/challang/app/common/exception/ErrorCode.java
  src/main/java/org/complete/challang/app/common/exception/ErrorResponse.java
  src/main/java/org/complete/challang/app/common/exception/GlobalExceptionHandler.java
  src/main/java/org/complete/challang/app/drink/controller/DrinkController.java
  src/main/java/org/complete/challang/app/drink/controller/dto/item/DrinkTypeDto.java
  src/main/java/org/complete/challang/app/drink/controller/dto/item/ManufacturerDto.java
  src/main/java/org/complete/challang/app/drink/controller/dto/item/PackageDto.java
  src/main/java/org/complete/challang/app/drink/controller/dto/request/DrinkCreateRequest.java
Labels: feature

#119 hotfix: 주류 조합 작성 및 상세보기 swagger request/response 오류 해결
  src/main/java/org/complete/challang/app/combination/controller/dto/item/CombinationCreateDto.java
  src/main/java/org/complete/challang/app/combination/controller/dto/item/CombinationFindDto.java
Labels: bug

#121 refactor: 메인 배너 리스트 조회시 어울리는 음식 상위 4개로 제한
  src/main/java/org/complete/challang/app/drink/domain/entity/view/DrinkFoodRank.java
  src/main/java/org/complete/challang/app/drink/domain/repository/DrinkCustomRepositoryImpl.java
Labels: feature, refactor

#124 feat: 주류 조합 게시글 리스트 조회, 수정, 삭제 구현
  src/main/java/org/complete/challang/app/combination/controller/CombinationController.java
  src/main/java/org/complete/challang/app/combination/controller/dto/item/CombinationCreateUpdateDto.java
  src/main/java/org/complete/challang/app/combination/controller/dto/request/CombinationBoardUpdateRequest.java
  src/main/java/org/complete/challang/app/combination/controller/dto/response/CombinationBoardCreateUpdateResponse.java
  src/main/java/org/complete/challang/app/combination/controller/dto/response/CombinationBoardListFindResponse.java
  src/main/java/org/complete/challang/app/combination/controller/dto/response/CombinationBoardPageResponse.java
  src/main/java/org/complete/challang/app/combination/domain/entity/Combination.java
  src/main/java/org/complete/challang/app/combination/domain/entity/CombinationBoard.java
  src/main/java/org/complete/challang/app/combination/domain/entity/CombinationSortCriteria.java
  src/main/java/org/complete/challang/app/combination/domain/repository/CombinationBoardCustomRepository.java
  src/main/java/org/complete/challang/app/combination/domain/repository/CombinationBoardCustomRepositoryImpl.java
  src/main/java/org/complete/challang/app/combination/domain/repository/CombinationBoardRepository.java
  src/main/java/org/complete/challang/app/combination/repository/CombinationBoardRepository.java
  src/main/java/org/complete/challang/app/combination/service/CombinationService.java
  src/main/java/org/complete/challang/app/common/exception/ErrorCode.java
  src/main/java/org/complete/challang/app/common/exception/SuccessCode.java
  src/main/java/org/complete/challang/app/drink/domain/entity/criteria/DrinkSortCriteria.java
Labels: feature

#126 feat: 주류 조합 리스트 조회에 유저 이미지 url 추가
  src/main/java/org/complete/challang/app/combination/controller/dto/response/CombinationBoardListFindResponse.java
  src/main/java/org/complete/challang/app/combination/domain/repository/CombinationBoardCustomRepository.java
  src/main/java/org/complete/challang/app/combination/domain/repository/CombinationBoardCustomRepositoryImpl.java
Labels: feature

#127 CI/CD Test
  src/main/java/org/complete/challang/app/combination/controller/CombinationController.java
  src/main/java/org/complete/challang/app/combination/controller/dto/item/CombinationCreateUpdateDto.java
  src/main/java/org/complete/challang/app/combination/controller/dto/request/CombinationBoardUpdateRequest.java
  src/main/java/org/complete/challang/app/combination/controller/dto/response/CombinationBoardCreateUpdateResponse.java
  src/main/java/org/complete/challang/app/combination/controller/dto/response/CombinationBoardListFindResponse.java
  src/main/java/org/complete/challang/app/combination/controller/dto/response/CombinationBoardPageResponse.java
  src/main/java/org/complete/challang/app/combination/domain/entity/Combination.java
  src/main/java/org/complete/challang/app/combination/domain/entity/CombinationBoard.java
  src/main/java/org/complete/challang/app/combination/domain/entity/CombinationSortCriteria.java
  src/main/java/org/complete/challang/app/combination/domain/repository/CombinationBoardCustomRepository.java
  src/main/java/org/complete/challang/app/combination/domain/repository/CombinationBoardCustomRepositoryImpl.java
  src/main/java/org/complete/challang/app/combination/domain/repository/CombinationBoardRepository.java
  src/main/java/org/complete/challang/app/combination/repository/CombinationBoardRepository.java
  src/main/java/org/complete/challang/app/combination/service/CombinationService.java
  src/main/java/org/complete/challang/app/common/exception/ErrorCode.java
  src/main/java/org/complete/challang/app/common/exception/SuccessCode.java
  src/main/java/org/complete/challang/app/drink/domain/entity/criteria/DrinkSortCriteria.java
Labels: chore

#130 feat: 주류 조합 게시글 좋아요/북마크 기능 구현
  src/main/java/org/complete/challang/app/combination/controller/CombinationController.java
  src/main/java/org/complete/challang/app/combination/controller/dto/response/CombinationBoardFindResponse.java
  src/main/java/org/complete/challang/app/combination/controller/dto/response/CombinationBoardListFindResponse.java
  src/main/java/org/complete/challang/app/combination/domain/entity/CombinationBoard.java
  src/main/java/org/complete/challang/app/combination/domain/entity/CombinationBoardBookmark.java
  src/main/java/org/complete/challang/app/combination/domain/entity/CombinationBoardLike.java
  src/main/java/org/complete/challang/app/combination/domain/repository/CombinationBoardCustomRepositoryImpl.java
  src/main/java/org/complete/challang/app/combination/service/CombinationService.java
  src/main/java/org/complete/challang/app/common/exception/ErrorCode.java
  src/main/java/org/complete/challang/app/common/exception/SuccessCode.java
Labels: feature, refactor
